export const projects = [
  {
    title: 'MERN Memories',
    description: "Using React, Node.js, Express & MongoDB this Full Stack MERN Application is a simple social media app that allows users to post interesting events that happened in their lives.",
    image: '/images/1.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/yash9657/Memories-App',
    visit: '#',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"A fully responsive, modern, fullstack online shop for my startup Farout Culture to sell shoes using Next JS for frontend and as backend endpoint, Stripe for payment gateway and Sanity for content management.",
    image: '/images/2.jpg',
    tags: ['Next JS', 'Stripe', 'Sanity'],
    source: 'https://github.com/yash9657/Ecommerce-website',
    visit: 'https://indianexpressnow.com/2023/05/04/farout-culture/',
    id: 1,
  },
  {
    title: 'WebRTC App',
    description: "A web app to make video calls based on unique chatroom IDs made with the help of React JS, Web RTC, Socket io.",
    image: '/images/3.jpg',
    tags: ['React', 'WebRTC', 'Socket.io'],
    source: 'https://github.com/yash9657/Video-Chat-App',
    visit: 'https://video-chat-app-aehr.netlify.app/',
    id: 2,
  },
  {
    title: 'Unichat',
    description: "This is a chat application with read receipts, file attachment functionality made using React JS, Chat Engine and Firebase for authentication.",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/yash9657/Unichat',
    visit: 'https://unichatrhee.netlify.app/',
    id: 3,
  },
  {
    title: 'Web 3.0',
    description: "Web 3.0 Decentralized cryptocurrency application with Metamask pairing, Smart Contract data fetching and ability to create ERC20 tokens.",
    image: '/images/5.png',
    tags: ['React', 'Metamask'],
    source: 'https://github.com/yash9657/decentralized-app',
    visit: '#',
    id: 4,
  },
  {
    title: 'Movie Recommendation Engine',
    description: "Movie recommender systems using collaborative filtering on public datasets.",
    image: '/images/6.png',
    tags: ['React', 'Metamask'],
    source: 'https://github.com/yash9657/movie-recom',
    visit: '#',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Began undergraduate journey', },
  { year: 2020, text: 'Secured my first internship at Mainstreet following which I opened up an online business', },
  { year: 2021, text: 'Took part in Hackathons and Programming competitions', },
  { year: 2022, text: 'Secured my second internship at Vidyo AI', },
  { year: 2023, text: 'Secured my third internship at Bajaj Health', },
  { year: 2023, text: 'Graduated with a Bachelors degree and started pursuing Masters', },
];